apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-q6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-exam
  template:
    metadata:
      labels:
          app: devops-exam
    spec:
      containers:
      - name: dharam0092-devops
        image: "dharamwithdocker/devops-exam:latest"
