apiVersion: v1
kind: Service
metadata:
  name: service-q6
spec:
  type: NodePort
  selector:
    app: devops-exam
  ports:
    - port: 80
      #nodePort: 30909
      #protocol: TCP
      targetPort: 80

